// Generated by build.js. Caches the app so it opens offline; a new build gets a new cache name.
var CACHE = 'visuword-364de7c0ce72';
var FILES = ["./","index.html","manifest.webmanifest","icons/apple-touch-icon.png","icons/icon-192.png","icons/icon-512.png","icons/maskable-512.png"];
self.addEventListener('install', function(e) {
  e.waitUntil(caches.open(CACHE).then(function(c) { return c.addAll(FILES); }).then(function() { return self.skipWaiting(); }));
});
self.addEventListener('activate', function(e) {
  e.waitUntil(caches.keys().then(function(keys) {
    return Promise.all(keys.filter(function(k) { return k.indexOf('visuword-') === 0 && k !== CACHE; }).map(function(k) { return caches.delete(k); }));
  }).then(function() { return self.clients.claim(); }));
});
self.addEventListener('fetch', function(e) {
  var req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  // the page: network first so updates show up, cache when offline
  if (req.mode === 'navigate') {
    e.respondWith(fetch(req).then(function(res) {
      var copy = res.clone();
      caches.open(CACHE).then(function(c) { c.put('index.html', copy); });
      return res;
    }).catch(function() { return caches.match('index.html'); }));
    return;
  }
  e.respondWith(caches.match(req).then(function(hit) { return hit || fetch(req); }));
});
